workspace:
  base: /lua
  path: src/git.kokolor.es/imo/emoji-downloader

pipeline:
  lint:
    image: imo/luarocks5.3:latest
    commands:
      - luarocks install luacheck
      - luacheck emoji-downloader.lua
